flowers = [
  [
    [
      [
        ["poppy", "zinnia", "cosmo", "poinsettia"],
        ["azalea", "carnation", "zinnia", "amaryllis"],
        ["tulip", "petunia", "amaranthus", "camelia"],
        ["anemone", "rose", "anthurium", "cyclamen"]
      ],
      [
        ["azalea", "rose", "aster", "poinsettia"],
        ["tulip", "begonia", "zinnia", "camelia"],
        ["alstroemeria", "amaranthus", "armeria", "camelia"],
        ["anemone", "anthurium", "aster", "bergenia"]
      ],
      [
        ["armeria", "aster", "rhodedendron", "camelia"],
        ["rhododendron", "azalea", "bergenia", "amaryllis"],
        ["bergenia", "bleeding heart", "verbena", "poinsettia"],
        ["carnation", "armeria", "sweet pea", "cyclamen"]
      ],
      [
        ["daylily", "calla lily", "sunflower", "bergenia"],
        ["hellebore", "cardinal flower", "scarlet bee balm", "camelia"],
        ["peony", "coneflower", "salvia", "camelia"],
        ["poinsettia", "cosmos", "royal poinciana", "poinsettia"]
      ]
    ],
    [
      [
        ["ranunculus", "dahlia", "red valerian", "bergenia"],
        ["royal poinciana, alstroemeria", "red trumpet creeper", "camelia"],
        ["sweet pea", "daylily", "montbretia", "bergenia"],
        ["tulip", "gerbera daisy", "mask flower", "camelia"]
      ],
      [
        ["yarrow", "gladiolus", "gerbera daisy", "poinsettia"],
        ["peony", "lily", "freesia", "poinsettia"],
        ["sweet pea", "mask flower", "cosmo", "cyclamen"],
        ["ranunculus", "montbretia", "crysanthemum", "cyclamen"]
      ],
      [
        ["royal poinciana", "prickly pear", "calla lily", "crocus"],
        ["daylily", "ranunculus", "bergenia", "crocus"],
        ["tulip", "red trumpet creeper", "aster", "camelia"],
        ["peony", "red valerian", "armeria", "bergenia"]
      ],
      [
        ["tulip", "royal poinciana", "amaranthus", "crocus"],
        ["pansy", "salvia", "crysanthemum", "crocus"],
        ["viola", "scarlet bee balm", "mums", "cyclamen"],
        ["sweet pea", "verbena", "cosmos", "poinsettia"]
      ]
    ],
    [
      [
        ["tulip", "yarrow", "freesia", "poinsettia"],
        ["sweet pea", "nasturtium", "gerbera daisy", "crocus"],
        ["yarrow", "zinnia", "calla lily", "camelia"],
        ["tulip", "salvia", "amaranthus", "amaryllis"]
      ],
      [
        ["azalea", "sunflower", "cosmos", "amaryllis"],
        ["hellebore", "cardinal flower", "scarlet bee balm", "camelia"],
        ["anemone", "anthurium", "aster", "bergenia"],
        ["azalea", "rose", "aster", "poinsettia"]
      ],
      [
        ["peony", "lily", "freesia", "poinsettia"],
        ["azalea", "carnation", "zinnia", "amaryllis"],
        ["carnation", "armeria", "sweet pea", "cyclamen"],
        ["anemone", "anthurium", "aster", "bergenia"]
      ],
      [
        ["yarrow", "zinnia", "calla lily", "camelia"],
        ["azalea", "rose", "aster", "poinsettia"],
        ["pansy", "salvia", "crysanthemum", "crocus"],
        ["anemone", "anthurium", "aster", "bergenia"]
      ]
    ],
    [
      [
        ["poppy", "zinnia", "cosmo", "poinsettia"],
        ["peony", "lily", "freesia", "poinsettia"],
        ["anemone", "anthurium", "aster", "bergenia"],
        ["ranunculus", "montbretia", "crysanthemum", "cyclamen"]
      ],
      [
        ["azalea", "carnation", "zinnia", "amaryllis"],
        ["poinsettia", "cosmos", "royal poinciana", "poinsettia"],
        ["azalea", "rose", "aster", "poinsettia"],
        ["peony", "lily", "freesia", "poinsettia"]
      ],
      [
        ["rhododendron", "azalea", "bergenia", "amaryllis"],
        ["yarrow", "zinnia", "calla lily", "camelia"],
        ["pansy", "salvia", "crysanthemum", "crocus"],
        ["azalea", "rose", "aster", "poinsettia"]
      ],
      [
        ["peony", "lily", "freesia", "poinsettia"],
        ["carnation", "armeria", "sweet pea", "cyclamen"],
        ["anemone", "anthurium", "aster", "bergenia"],
        ["azalea", "carnation", "zinnia", "amaryllis"]
      ]
    ],
    [
      [
        ["azalea", "rose", "aster", "poinsettia"],
        ["rhododendron", "azalea", "bergenia", "amaryllis"],
        ["yarrow", "zinnia", "calla lily", "camelia"],
        ["tulip", "petunia", "amaranthus", "camelia"]
      ],
      [
        ["carnation", "armeria", "sweet pea", "cyclamen"],
        ["poinsettia", "cosmos", "royal poinciana", "poinsettia"],
        ["hellebore", "cardinal flower", "scarlet bee balm", "camelia"],
        ["ranunculus", "montbretia", "crysanthemum", "cyclamen"]
      ],
      [
        ["anemone", "anthurium", "aster", "bergenia"],
        ["yarrow", "gladiolus", "gerbera daisy", "poinsettia"],
        ["azalea", "carnation", "zinnia", "amaryllis"],
        ["tulip", "royal poinciana", "amaranthus", "crocus"],
      ],
      [
        ["pansy", "salvia", "crysanthemum", "crocus"],
        ["hellebore", "cardinal flower", "scarlet bee balm", "camelia"],
        ["azalea", "carnation", "zinnia", "amaryllis"],
        ["tulip", "petunia", "amaranthus", "camelia"]
      ]
    ],
    [
      [
        ["azalea", "carnation", "zinnia", "amaryllis"],
        ["poppy", "zinnia", "cosmo", "poinsettia"],
        ["azalea", "rose", "aster", "poinsettia"],
        ["yarrow", "gladiolus", "gerbera daisy", "poinsettia"]
      ],
      [
        ["yarrow", "gladiolus", "gerbera daisy", "poinsettia"],
        ["hellebore", "cardinal flower", "scarlet bee balm", "camelia"],
        ["anemone", "anthurium", "aster", "bergenia"],
        ["rhododendron", "azalea", "bergenia", "amaryllis"]
      ],
      [
        ["poinsettia", "cosmos", "royal poinciana", "poinsettia"],
        ["pansy", "salvia", "crysanthemum", "crocus"],
        ["tulip", "petunia", "amaranthus", "camelia"],
        ["ranunculus", "montbretia", "crysanthemum", "cyclamen"]
      ],
      [
        ["azalea", "carnation", "zinnia", "amaryllis"],
        ["poppy", "zinnia", "cosmo", "poinsettia"],
        ["yarrow", "zinnia", "calla lily", "camelia"],
        ["anemone", "anthurium", "aster", "bergenia"],
      ]
    ]
  ], [
    [
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ]
    ],
    [
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ]
    ],
    [
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ]
    ],
    [
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ]
    ],
    [
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ]
    ],
    [
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ]
      ]], [
    [
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ]
    ],
    [
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ]
    ],
    [
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ]
    ],
    [
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ]
    ],
    [
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ]
    ],
    [
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ]
      ]], [
    [
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ]
    ],
    [
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ]
    ],
    [
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ]
    ],
    [
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ]
    ],
    [
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ]
    ],
    [
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ]
      ]], [
    [
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ]
    ],
    [
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ]
    ],
    [
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ]
    ],
    [
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ]
    ],
    [
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ]
    ],
    [
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ]
      ]], [
    [
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ]
    ],
    [
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ]
    ],
    [
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ]
    ],
    [
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ]
    ],
    [
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ]
    ],
    [
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ]
      ]], [
    [
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ]
    ],
    [
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ]
    ],
    [
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ]
    ],
    [
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ]
    ],
    [
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ]
    ],
    [
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ],
      [
        [],
        [],
        [],
        []
      ]
      ]]]
